# Generated by Django 2.2.12 on 2023-09-05 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(choices=[('usa', 'United Status America'), ('ca', 'canada'), ('kwt', 'kewit'), ('egy', 'egypt'), ('ksa', 'saudi')], max_length=20)),
                ('to_location', models.CharField(choices=[('usa', 'United Status America'), ('ca', 'canada'), ('kwt', 'kewit'), ('egy', 'egypt'), ('ksa', 'saudi')], max_length=20)),
                ('name_shipment', models.CharField(max_length=20)),
                ('before_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=500)),
                ('user_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_link', models.URLField()),
                ('item_name', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('item_weight', models.FloatField()),
                ('single_item_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.Shipment')),
            ],
        ),
    ]
