# Generated by Django 2.2.12 on 2023-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='before_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
