# Generated by Django 2.2.12 on 2023-09-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20230905_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='trip_id',
            new_name='trip_object',
        ),
    ]
