# Generated by Django 4.2.3 on 2023-09-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_auto_20230905_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='notes',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='before_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
