# Generated by Django 2.2.12 on 2023-09-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location_from', models.CharField(choices=[('usa', 'United Status America'), ('ca', 'canada'), ('kwt', 'kewit'), ('egy', 'egypt'), ('ksa', 'saudi')], max_length=10)),
                ('location_to', models.CharField(choices=[('usa', 'United Status America'), ('ca', 'canada'), ('kwt', 'kewit'), ('egy', 'egypt'), ('ksa', 'saudi')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_available', models.FloatField()),
            ],
        ),
    ]
